---
- name: Import EPEL role
  ansible.builtin.include_role:
    name: diademiemi.epel

- name: Install solaar
  become: true
  ansible.builtin.yum:
    name: solaar
    state: present
    update_cache: true

...
