---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if /usr/bin/solaar exists
      ansible.builtin.stat:
        path: /usr/bin/solaar
      register: solaar_stat

    - name: Fail if solaar does not exist
      ansible.builtin.fail:
        msg: "Test failed"
      when: not solaar_stat.stat.exists

...
